page1/urls.py
from django.urls import path
from .views import CreateView,DetailView,add_product

app_name = 'page1'

urlpatterns = [
    path('',CreateView),
    path('detail/<int:pk>',DetailView,name='detail'),
    path('addprod/',add_product,name='addprod'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/',include('page1.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

page1/models.py
from django.db import models

# Create your models here.

class Prodcuts(models.Model):
    name = models.CharField(max_length=250)
    price = models.IntegerField()
    description = models.CharField(max_length=500)
    image = models.ImageField(blank=True,upload_to='images')

    def __str__(self) :
        return self.name

page1/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from .models import Prodcuts


# Create your views here.

def CreateView(request):
    Products = Prodcuts.objects.all()
    context = {
        'Products' : Products
    }
    return render(request,'home.html',context)


def DetailView(request,pk):
    Product = Prodcuts.objects.get(id=pk)
    context = {
        'Product' : Product
    }
    return render(request,'detail.html',context)


def add_product(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        desc = request.POST.get("desc")
        image = request.FILES["upload"]
        prod = Prodcuts(name=name,price=price,description=desc,image=image)
        prod.save()
    
    return render(request,'addprod.html')

page1/templates/addprod.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input placeholder="Name" type="text" name="name" id="name">
    <input placeholder="Price" type="text" name="price" id="price">
    <input placeholder="Desc" type="text" name="desc" id="desc">
    <input type="file" accept="image/*" name="upload" id="upload">
    <input type="submit" name="" id="">
</form>

page1/templates/base.html
{% load static %}
<html>
    <head>
      <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
      <nav class="bg-white shadow-lg">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
               <div class="flex space-x-7">
                  <div>
                    <a href="#" class="flex px-2 py-4 items-center">
                        <img class="h-8 w-8" src="{% static 'images/shopping.png' %}" alt="">
                        <span class="text-gray-500 text-lg font-semibold">Buy&Sell</spam>
                    </a>
                  </div>
                  <div class="items-center spcae-x-1 flex">
                    <a href="#" class="px-2 py-4 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                    <a href="#" class="px-2 py-4 text-gray-500 font-semibold">About</a>
                    <a href="#" class="px-2 py-4 text-gray-500 font-semibold">Contact</a>
                  </div>
               </div>
           </div>
        </div>
    </nav>
        {% block content %}

        {% endblock%}
    </body>

</html>

page1/templates/detail.html
{% extends 'base.html' %}
{% block content%}
<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{Product.image.url}}" alt="img">
    <div class="w-2/3 text-xl ml-5 mt-10">
        <div class="mt-5">{{ Product.name}}</div>
        <div class="mt-5 text-green-500">${{ Product.price }}</div>
        <div class="mt-5 text-gray-800">{{ Product.description }}</div>
    </div>
</div>
{% endblock %}
    

page1/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <!-- starts here-->
 <main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
      <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl text-gray-900 font-extrabold sm:text-5xl md:text-6xl">
          <span class="block xl:inline">Premium Products</span>
          <span class="block text-green-500 xl:inline">Non-premium Prices</span>
        </h1>
        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality products with free shipping</p>
      </div>
 </main>
 <!-- ends here -->

 <div class="flex mt-5 p-10 justify-center">
   <h2 class="text-3xl font-bold mt-0 mb-2 text-gray-500">Available Products</h2>
 </div>
 <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5"> 
  {% for prod in Products %}
  <a href="{% url 'page1:detail' prod.id %}">
  <div class="rounded overflow-hidden shadow-lg">
    <img class = "w-full" src="{{prod.image.url}}" alt="img">
    <div class="px-6 py-4">
      <div class="font-bold text-xl mb-2">
          {{prod.name}}
      </div>
      <div class="font-bold text-xl text-green-500 mb-2">
        ${{prod.price}}
      </div>
    </div>
   
  </div>
  </a>
  {% endfor %}
 </div>
{% endblock %}
    